name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build single-file executable
        shell: powershell
        run: .\build.ps1
      - uses: actions/upload-artifact@v7
        with:
          name: LanSwitch
          path: dist/LanSwitch.exe
